import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
    title: 'AI Generated Landing Page',
    description: 'Premium landing page generated by AI',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
